### ISSUE TITLE
POI State Diagram

### ISSUE THREAD

**Issue by u12206522** [RitzDoolabh/COS301-Team_Fortran#6]

**Comment by u12206522** [comment]
![poi_state_diagram](https://cloud.githubusercontent.com/assets/25883921/23742975/9e998534-04b7-11e7-8b03-a67e89ac06d4.jpg)

Please review and make necessary changes on the xml file?

**Comment by josephletsoalo** [comment]
![sequantial](https://cloud.githubusercontent.com/assets/25735050/23763131/1fa97ce4-0501-11e7-9c76-805cf50970a8.jpg)
